### ISSUE TITLE
Floating view ordering not working

### ISSUE THREAD

**Issue by Luminarys** [SirCmpwn/sway#149]
Floating views aren't being arranged properly on click(the clicked view should come to the front). Currently nothing happens on click. In addition, all floating views which aren't in the front have mouse motion and mouse clicking ignored.

**Comment by taiyu-len** [comment]
first part should be fixed, but i wasnt having the mouse motion/mouse click ignored problem.

**Comment by Luminarys** [comment]
I'll check again.

**Comment by Luminarys** [comment]
The mouse motion/click ignoring was a side effect I think, but there's still an issue. When you drag a floating view which is not at the front, it isn't moved to the front, i.e. you move/resize the floating view, but it still stays behind the other ones.

**Comment by taiyu-len** [comment]
that should do it. just a bit of reordering.

**Comment by Luminarys** [comment]
Fixed.
