### ISSUE TITLE
Screen first rendered after moving mouse

### ISSUE THREAD

**Issue by onny** [SirCmpwn/sway#509]
Hi,
after starting sway the screen is black and only the mouse cursor is visible. After moving the mouse, wallpaper and swaybar gets rendered and is working fine then.

Its not a major bug but somehow confusing.

Best regards,
Jonas

**Comment by SirCmpwn** [comment]
By the way, @Cloudef, you might want to do something like this in wlc. I've always felt like this was wlc's problem.

**Comment by SirCmpwn** [comment]
My bad - this does not seem to have been fixed by #510.

**Comment by SirCmpwn** [comment]
cc @mikkeloscar

**Comment by mikkeloscar** [comment]
For anyone where #510 doesn't fix the issue, could you please post your sway config? Also please try to launch sway from inside X and from a tty and see if that makes a difference. That will help debug the issue.

And as always, make sure wlc and sway are up to date :)

**Comment by SirCmpwn** [comment]
[No problem](https://sr.ht/kss6.txt)

**Comment by SirCmpwn** [comment]
Does not occur when running sway under X.

**Comment by SirCmpwn** [comment]
Correction - it works for me now. The only change I've made recently is that I'm running a debug build of wlc, not sure if it's related.

**Comment by SirCmpwn** [comment]
@onny can you confirm if this is still an issue for you?

**Comment by raycewest** [comment]
It still is for me.  I can upload config later if wanted.

**Comment by mikkeloscar** [comment]
I think it's a race issue where swaybg starts too late in some cases, to be affected by the forced render request. I just haven't had time to look into it yet.

**Comment by onny** [comment]
It looks fine now for me, thanks :)

**Comment by raycewest** [comment]
@mikkeloscar Indeed, twice out of the ten or so times I just restarted it to see, it rendered properly from the get-go.  The other times were nothing until I moved the mouse.

**Comment by mikkeloscar** [comment]
Please test #512 if you can, that should be the correct fix for this issue!
